version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - appnet

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      REDIS_URL: redis://redis:6379
    command: >
      sh -c 'npx sequelize-cli db:migrate --config src/infrastructure/database/config/config.js --migrations-path src/interfaces/http/migrations && npm start'
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/dist/src/uploads
    networks:
      - appnet

  frontend:
    build:
      context: ../task-deck-web
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3000"
    networks:
      - appnet

volumes:
  pgdata:
  uploads:

networks:
  appnet:
    name: appnet
